#!/usr/bin/env python3
"""Check every program of the tutorial against what its comments claim.

Usage
-----

    python3 scripts/check.py                    every program under examples/
    python3 scripts/check.py examples/07        the programs of one folder
    python3 scripts/check.py examples/07/a.dsp  one program

or, from the top of the repository, `make check` and `make check DIR=examples/07`.
It prints one line per program, `ok    PATH (N checks)` or `FAIL  PATH`
followed by the problems found, then `K/N programs checked`. The exit status
is 0 when every program passes, 1 otherwise.

Tools
-----

The environment names the tools; the defaults suppose the checkouts of the
tutorial, faust-rs and faustlibraries side by side:

    FAUST           the C++ Faust compiler (default `faust`, from the PATH)
    FAUSTPROBE      faust-rs's measuring tool
                    (default ../faust-rs/target/release/faustprobe)
    FAUSTLIBRARIES  the standard libraries (default ../../faustlibraries)

Both compilers get `-I` for the program's own folder (for the tutorial's
.lib files) and for FAUSTLIBRARIES.

What is checked
---------------

The checks are written in the program itself, as comment lines that the
compilers ignore. For each .dsp file:

1. the C++ Faust compiler must compile it (unless it has a `// cpp: no`
   line, kept for the faust-rs extensions);
2. faustprobe must compile and render it (one frame, zero input);
3. each `// check: ARGS` line runs `faustprobe ARGS file.dsp`, which must
   succeed (exit status 0); each `// expect: REGEX` line that follows must
   match its output (stdout and stderr together, one line at a time for
   `^` and `$`). The command runs in the file's folder, so that
   `--compare other.dsp` works. A `// check-fails: ARGS` line expects a
   failure instead;
4. a file marked `// expect-error` shows an error: both compilers must
   reject it, and each `// expect:` line placed before any `check` line
   must match faustprobe's message;
5. `// cpp-expect: REGEX` and `// cpp-absent: REGEX` lines must, and must
   not, match the C++ code that `faust` generates for the file;
6. a file with a `// faust-rs: no` line is checked with the C++ compiler
   only (for a construct faust-rs does not handle yet; the line says why).


An example, from examples/07/adsr_velocity.dsp:

    // check: --double --sr 48000 -n 48000 --in zero --at 0 velocity=0.5 --quiet
    // expect: out0: peak=1\.0 .*peak_at=479
    // expect: out1: peak=0\.5 .*peak_at=479

The directives, one per line, anywhere in the file (conventionally at its end):

    // check: ARGS          run `faustprobe ARGS file.dsp`; it must succeed
    // check-fails: ARGS    the same, but it must fail (exit status not 0)
    // expect: REGEX        after a check: must match that check's output;
                            after `expect-error` and before any check: must
                            match the error message
    // expect-error         the program must not compile
    // cpp-expect: REGEX    must match the C++ code generated by `faust`
    // cpp-absent: REGEX    must not match it
    // cpp: no              skip the C++ compiler (faust-rs extensions)
    // faust-rs: no         skip faustprobe (C++ compiler only)

REGEX is a Python regular expression, searched with re.MULTILINE: `^` and
`$` match at the start and end of each line of the output. ARGS is split
like a shell command line (quotes are honoured).
"""
import os
import re
import shlex
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FAUST = os.environ.get("FAUST", "faust")
FAUSTPROBE = os.environ.get("FAUSTPROBE", os.path.join(ROOT, "..", "faust-rs", "target", "release", "faustprobe"))
LIBS = os.path.abspath(os.environ.get("FAUSTLIBRARIES", os.path.join(ROOT, "..", "..", "faustlibraries")))
FAUSTPROBE = os.path.abspath(FAUSTPROBE) if os.sep in FAUSTPROBE else FAUSTPROBE


def programs(args):
    """Yield the .dsp files to check, as absolute paths, in a stable order.

    args: the command-line arguments, files or folders. Folders are walked
    recursively, sorted by name. No argument means the whole examples/ tree.
    """
    targets = args or [os.path.join(ROOT, "examples")]
    for t in targets:
        t = os.path.abspath(t)
        if os.path.isfile(t):
            yield t
            continue
        for d, _, files in sorted(os.walk(t)):
            for f in sorted(files):
                if f.endswith(".dsp"):
                    yield os.path.join(d, f)


def directives(path):
    """Read the checking directives of one program.

    Returns a tuple (cpp, checks, error, cpp_expect, cpp_absent, probe):

    cpp         False when the file has `// cpp: no` (skip the C++ compiler)
    checks      list of {"fails": bool, "args": [str], "expect": [regex]},
                one per `check` or `check-fails` line, each with the `expect`
                lines that follow it
    error       None, or the list of `expect` regexes of an `expect-error`
                program placed before its first check
    cpp_expect  regexes that the generated C++ must contain
    cpp_absent  regexes that it must not contain
    probe       False when the file has `// faust-rs: no` (skip faustprobe)
    """
    checks = []
    cpp = True
    error = None
    cpp_expect, cpp_absent = [], []
    probe = True
    for line in open(path, encoding="utf-8"):
        s = line.strip()
        if s.startswith("// cpp: no"):
            cpp = False
        if s.startswith("// faust-rs: no"):
            probe = False
        if s.startswith("// expect-error"):
            error = []
            continue
        m = re.match(r"//\s*cpp-(expect|absent):\s*(.*)$", s)
        if m:
            (cpp_expect if m.group(1) == "expect" else cpp_absent).append(m.group(2))
            continue
        m = re.match(r"//\s*(check|check-fails):\s*(.*)$", s)
        if m:
            checks.append({"fails": m.group(1) == "check-fails", "args": shlex.split(m.group(2)), "expect": []})
            continue
        m = re.match(r"//\s*expect:\s*(.*)$", s)
        if m and checks:
            checks[-1]["expect"].append(m.group(1))
        elif m and error is not None:
            error.append(m.group(1))
    return cpp, checks, error, cpp_expect, cpp_absent, probe


def run(cmd, cwd=None):
    """Run cmd (a list) in cwd; return its exit status and stdout + stderr."""
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    return r.returncode, r.stdout + r.stderr


def shorten(out, head=20, tail=8):
    """Keep the first `head` and last `tail` lines of a long output for a report."""
    lines = out.splitlines()
    if len(lines) <= head + tail + 1:
        return out
    return "\n".join(lines[:head] + [f"... ({len(lines) - head - tail} lines)"] + lines[-tail:])


def main():
    """Check the programs named on the command line; return the exit status."""
    failures = 0
    count = 0
    for path in programs(sys.argv[1:]):
        count += 1
        rel = os.path.relpath(path, ROOT)
        inc = ["-I", os.path.dirname(path), "-I", LIBS]
        cpp, checks, error, cpp_expect, cpp_absent, probe = directives(path)
        if not probe:
            checks = []
        problems = []
        # A program that must not compile: both compilers must reject it,
        # and its message must match; nothing else is checked.
        if error is not None:
            rc, out = run([FAUST, *inc, path, "-o", os.devnull])
            if rc == 0:
                problems.append("faust C++ accepted a program marked expect-error")
            rc, out = run([FAUSTPROBE, "--double", *inc, "-n", "1", "--in", "zero", "--quiet", path])
            if rc == 0:
                problems.append("faustprobe accepted a program marked expect-error")
            for e in error:
                if not re.search(e, out, re.MULTILINE):
                    problems.append(f"error message: {e!r} not found in\n{out}")
            checks = []
            cpp = None
        # The C++ compiler, whose output is the generated code.
        if cpp:
            rc, out = run([FAUST, *inc, path])
            if rc != 0:
                problems.append("faust C++:\n" + shorten(out))
            else:
                for e in cpp_expect:
                    if not re.search(e, out, re.MULTILINE):
                        problems.append(f"cpp-expect {e!r} not found in the generated C++")
                for e in cpp_absent:
                    if re.search(e, out, re.MULTILINE):
                        problems.append(f"cpp-absent {e!r} found in the generated C++")
        # faustprobe must at least compile and render one frame.
        if cpp is not None and probe:
            rc, out = run([FAUSTPROBE, "--double", *inc, "-n", "1", "--in", "zero", "--quiet", path])
            if rc != 0:
                problems.append("faustprobe (compile):\n" + out)
        # The checks, run in the program's folder so that a check can name a
        # neighbour (`--compare other.dsp`).
        for c in checks:
            rc, out = run([FAUSTPROBE, *inc, *c["args"], path], cwd=os.path.dirname(path))
            what = " ".join(c["args"])
            if c["fails"] and rc == 0:
                problems.append(f"check-fails {what}: succeeded")
            elif not c["fails"] and rc != 0:
                problems.append(f"check {what}: exit status {rc}\n{shorten(out)}")
            for e in c["expect"]:
                if not re.search(e, out, re.MULTILINE):
                    problems.append(f"check {what}: {e!r} not found in\n{shorten(out)}")
        if problems:
            failures += 1
            print(f"FAIL  {rel}")
            for p in problems:
                print("    " + p.replace("\n", "\n    ").rstrip())
        else:
            note = "" if probe else ", C++ only"
            print(f"ok    {rel} ({len(checks)} check{'s' if len(checks) != 1 else ''}{note})")
    print(f"\n{count - failures}/{count} programs checked")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
